version: '2'
services:
  manager-app:
    image: manager
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://manager-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=manager
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  manager-mongodb:
    extends:
      file: mongodb.yml
      service: manager-mongodb
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
